spring:
  application:
    name: test   #测试环境
  profiles: eureka-config-cilent
eureka:
  client:
    service-url:
     defaultZone: http://127.0.0.1:8761/eureka
server:
  port: 8001


---
spring:
  application:
    name: dev   #开发环境
  profiles: eureka-config-cilent
eureka:
  client:
    service-url:
     defaultZone: http://127.0.0.1:8761/eureka
server:
  port: 8002
