spring:
  application:
    name: eureka-config-cilent   #测试环境
  profiles: test
eureka:
  client:
    service-url:
     defaultZone: http://127.0.0.1:8761/eureka
server:
  port: 8001


---
spring:
  application:
    name: eureka-config-cilent   #开发环境
  profiles: dve
eureka:
  client:
    service-url:
     defaultZone: http://127.0.0.1:8761/eureka
server:
  port: 8002
